name: formstack
description: A  flutter library to create a UI based on the model from either json or dart object.
version: 1.1.0
homepage: https://github.com/sudhi001/FormStack
issue_tracker: https://github.com/sudhi001/FormStack/issues
screenshots:
  - description: 'Logo of formstack framework'
    path: screenshots/logo.png

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  rxdart: ^0.28.0
  dio: ^5.9.0
  uuid: ^4.5.2
  web: ^1.1.1
  reviews_slider: ^2.0.0
  lottie: ^3.3.2
  collection: ^1.19.1
  file_picker: ^10.3.7
  # flutter_quill: ^8.4.0
  google_maps_flutter_web: ^0.5.14+3
  google_maps_flutter: ^2.14.0
  location: ^8.0.1
  google_maps: ^8.1.1
  http: ^1.6.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottiefiles/
    - screenshots/logo.png

